# Generated by Django 5.0 on 2023-12-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_paid',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
