# Generated by Django 5.0 on 2023-12-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservation_date_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='checkout',
            field=models.BooleanField(default=False),
        ),
    ]
