# Generated by Django 5.0 on 2023-12-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='img_url',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
