# Generated by Django 5.0 on 2023-12-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_hotel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.IntegerField(),
        ),
    ]
